# Generated by Django 5.2.8 on 2026-03-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="extra_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
