# Generated by Django 5.2.8 on 2026-02-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domain",
            name="tenant",
        ),
        migrations.AlterModelOptions(
            name="opco",
            options={},
        ),
        migrations.AddField(
            model_name="opco",
            name="plan",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("pro", "Pro"),
                    ("enterprise", "Enterprise"),
                ],
                default="free",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="opco",
            name="region",
            field=models.CharField(default="global", max_length=50),
        ),
        migrations.AlterField(
            model_name="opco",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.DeleteModel(
            name="Domain",
        ),
    ]
