# Generated by Django 5.2.8 on 2026-02-25 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_domain_tenant_alter_opco_options_opco_plan_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="opco",
            options={
                "verbose_name": "شركة مشغلة",
                "verbose_name_plural": "الشركات المشغلة",
            },
        ),
        migrations.AddField(
            model_name="opco",
            name="is_holding",
            field=models.BooleanField(
                default=False,
                help_text="حدد هذا الخيار إذا كانت هذه الشركة تمتلك شركات أخرى تحتها",
                verbose_name="شركة قابضة؟",
            ),
        ),
        migrations.AddField(
            model_name="opco",
            name="is_system_root",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="شركة أساسية للنظام"
            ),
        ),
        migrations.AddField(
            model_name="opco",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subsidiaries",
                to="core.opco",
                verbose_name="الشركة الأم",
            ),
        ),
    ]
