# Generated by Django 5.2.8 on 2026-02-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_opco_options_opco_is_holding_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opco",
            name="cr_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="السجل التجاري"
            ),
        ),
        migrations.AddField(
            model_name="opco",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="company_logos/",
                verbose_name="شعار الشركة",
            ),
        ),
        migrations.AddField(
            model_name="opco",
            name="tax_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="الرقم الضريبي"
            ),
        ),
    ]
