# Generated by Django 5.2.8 on 2026-03-08 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_companyuser"),
        ("item_master", "0007_delete_fielddefinition_alter_category_options_and_more"),
        ("wms", "0003_alter_storagebin_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opco",
            name="is_system_root",
            field=models.BooleanField(default=False, verbose_name="شركة أساسية للنظام"),
        ),
        migrations.CreateModel(
            name="PutawayRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_bin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wms.storagebin",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="item_master.material",
                    ),
                ),
                (
                    "opco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.opco"
                    ),
                ),
            ],
            options={
                "unique_together": {("item", "opco")},
            },
        ),
    ]
