# Generated by Django 5.2.8 on 2026-02-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmove",
            name="payment_term",
            field=models.CharField(default="CASH", max_length=50),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="receipt_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="unit_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="vendor_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
