# Generated by Django 5.2.8 on 2026-02-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wms", "0002_stockmove_payment_term_stockmove_receipt_type_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="storagebin",
            unique_together={("code", "storage_location")},
        ),
    ]
