# Generated by Django 5.2.8 on 2026-02-20 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="FieldDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_model",
                    models.CharField(
                        choices=[
                            ("material", "Material"),
                            ("vendor", "Vendor"),
                            ("po", "PO"),
                            ("location", "Location"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("label", models.CharField(max_length=100)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("bool", "Checkbox"),
                            ("select", "Select"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("options", models.JSONField(blank=True, default=list)),
            ],
            options={
                "unique_together": {("target_model", "name")},
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("base_uom", models.CharField(default="PCS", max_length=10)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="item_master.category",
                    ),
                ),
            ],
        ),
    ]
