# Generated by Django 5.2.8 on 2026-02-20 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("item_master", "0001_initial"),
        ("wms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="default_bin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_materials",
                to="wms.storagebin",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="default_plant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_materials",
                to="wms.plant",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="opco",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="core.opco",
            ),
        ),
    ]
