# Generated by Django 5.2.8 on 2026-02-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_domain_tenant_alter_opco_options_opco_plan_and_more"),
        ("item_master", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="barcode",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="material",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name="material",
            unique_together={("opco", "sku")},
        ),
    ]
