# Generated by Django 5.2.8 on 2026-02-23 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item_master", "0003_material_barcode_material_is_active_and_more"),
        ("wms", "0002_stockmove_payment_term_stockmove_receipt_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="default_bin",
        ),
        migrations.RemoveField(
            model_name="material",
            name="default_plant",
        ),
        migrations.CreateModel(
            name="MaterialLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_bins",
                        to="item_master.material",
                    ),
                ),
                (
                    "storage_bin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wms.storagebin"
                    ),
                ),
            ],
            options={
                "unique_together": {("material", "storage_bin")},
            },
        ),
        migrations.AddField(
            model_name="material",
            name="storage_locations",
            field=models.ManyToManyField(
                related_name="materials",
                through="item_master.MaterialLocation",
                to="wms.storagebin",
            ),
        ),
    ]
