# Generated by Django 5.2.8 on 2026-02-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item_master", "0004_remove_material_default_bin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="materials/"),
        ),
    ]
