# Generated by Django 5.2.8 on 2026-02-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item_master", "0005_material_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="max_level",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="material",
            name="reorder_level",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
