# Generated by Django 5.2.8 on 2026-03-08 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item_master", "0006_material_max_level_material_reorder_level"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FieldDefinition",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
        migrations.AlterModelOptions(
            name="materiallocation",
            options={"ordering": ["sequence"]},
        ),
        migrations.RemoveField(
            model_name="material",
            name="base_uom",
        ),
        migrations.RemoveField(
            model_name="material",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="material",
            name="extra_data",
        ),
        migrations.RemoveField(
            model_name="material",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="material",
            name="storage_locations",
        ),
        migrations.RemoveField(
            model_name="material",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="category",
            name="default_putaway_strategy",
            field=models.CharField(
                choices=[
                    ("fixed", "Fixed Bin (الرف الثابت)"),
                    ("closest", "Closest Location (الأقرب)"),
                    ("fifo", "FIFO (الأقدم أولاً)"),
                ],
                default="fixed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="item_master.category",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="is_template",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="material",
            name="tracking",
            field=models.CharField(
                choices=[
                    ("none", "No Tracking (بدون تتبع)"),
                    ("serial", "By Unique Serial (سيريال رقمي)"),
                    ("lot", "By Lots/Batch (رقم التشغيلة)"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="volume",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="material",
            name="weight",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="materiallocation",
            name="sequence",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="category",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="material",
            name="barcode",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
