# Generated by Django 5.2.8 on 2026-03-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item_master", "0007_delete_fielddefinition_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="base_uom",
            field=models.CharField(default="PCS", max_length=50),
        ),
    ]
