# Generated by Django 5.2.8 on 2026-03-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item_master", "0008_material_base_uom"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
