# Generated by Django 5.2.8 on 2026-03-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item_master", "0009_material_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="standard_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
