# Generated by Django 5.2 on 2026-05-23

from django.db import migrations, models
import django.db.models.deletion
import uuid

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('item_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم الوصفة (مثال: وصفة برجر لحم دبل)', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('preparation_time', models.IntegerField(default=0, help_text='وقت التحضير بالدقائق')),
                ('kitchen_station', models.CharField(choices=[('grill', 'الجريل (Grill)'), ('bar', 'البار والمشروبات (Bar)'), ('salads', 'المقبلات والسلطات (Salads)'), ('pizza', 'البيتزا والمعجنات (Pizza)'), ('dessert', 'الحلويات (Dessert)')], default='grill', max_length=50)),
                ('finished_good', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='item_master.material')),
                ('opco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.opco')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, help_text='الكمية المراد خصمها من المخزن', max_digits=10)),
                ('uom', models.CharField(default='KG', help_text='وحدة القياس (مثال: جرام، مل، حبة)', max_length=20)),
                ('is_removable', models.BooleanField(default=True, help_text='هل يمكن للعميل طلب إزالة هذا المكون؟')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_recipes', to='item_master.material')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='restaurant_pos.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=False)),
                ('min_choices', models.IntegerField(default=0)),
                ('max_choices', models.IntegerField(default=1)),
                ('opco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.opco')),
            ],
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('extra_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('material_qty', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='restaurant_pos.modifiergroup')),
                ('linked_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item_master.material')),
            ],
        ),
        migrations.CreateModel(
            name='POSSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cashier_name', models.CharField(max_length=100)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('expected_closing_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('actual_closing_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('opco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.opco')),
            ],
        ),
        migrations.CreateModel(
            name='POSCashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'إيداع'), ('OUT', 'صرف / مصاريف')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='restaurant_pos.possession')),
            ],
        ),
        migrations.CreateModel(
            name='POSOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref', models.CharField(max_length=50, unique=True)),
                ('order_type', models.CharField(choices=[('DINE_IN', 'Dine In (محلي)'), ('TAKEAWAY', 'Takeaway (سفري)'), ('DELIVERY', 'Delivery (توصيل)')], default='TAKEAWAY', max_length=20)),
                ('table_number', models.CharField(blank=True, max_length=20, null=True)),
                ('guest_count', models.IntegerField(default=1)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash (كاش)'), ('credit', 'Credit (آجل)'), ('instapay', 'InstaPay (إلكتروني)')], default='cash', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft (لم يدفع)'), ('paid', 'Received (تم الاستلام - في المطبخ)'), ('inprogress', 'In Progress (جاري التحضير)'), ('done', 'Done (جاهز للاستلام)'), ('refunded', 'Refunded (مرتجع)'), ('cancelled', 'Cancelled (ملغي)')], default='draft', max_length=20)),
                ('is_refunded', models.BooleanField(default=False)),
                ('kitchen_received_at', models.DateTimeField(blank=True, null=True)),
                ('kitchen_started_at', models.DateTimeField(blank=True, null=True)),
                ('kitchen_done_at', models.DateTimeField(blank=True, null=True)),
                ('kitchen_cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('inventory_deducted', models.BooleanField(default=False)),
                ('opco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.opco')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurant_pos.possession')),
            ],
        ),
        migrations.CreateModel(
            name='POSOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kitchen_notes', models.TextField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_master.material')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='restaurant_pos.posorder')),
            ],
        ),
    ]
