# Generated by Django 5.2 on 2026-05-23

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_pos', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم الدور (مثال: الدور الأول)', max_length=100)),
                ('number', models.IntegerField(default=1, help_text='رقم ترتيب الدور')),
                ('is_active', models.BooleanField(default=True)),
                ('opco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.opco')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('opco', 'number')},
            },
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='رقم أو اسم الترابيزة', max_length=50)),
                ('seats_limit', models.IntegerField(default=4, help_text='عدد الكراسي المخصصة للترابيزة')),
                ('current_guests', models.IntegerField(default=0, help_text='عدد الأفراد المتواجدين حالياً')),
                ('status', models.CharField(choices=[('available', 'متاح (Available)'), ('occupied', 'مشغول (Occupied)'), ('reserved', 'محجوز (Reserved)'), ('cleaning', 'تنظيف (Cleaning)')], default='available', max_length=20)),
                ('shape', models.CharField(choices=[('square', 'مربع (Square)'), ('round', 'دائري (Round)')], default='square', max_length=20)),
                ('position_x', models.IntegerField(default=50, help_text='الموقع الأفقي X (%)')),
                ('position_y', models.IntegerField(default=50, help_text='الموقع الرأسي Y (%)')),
                ('active_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_table', to='restaurant_pos.posorder')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurant_pos.restaurantfloor')),
                ('opco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.opco')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('opco', 'floor', 'number')},
            },
        ),
    ]
